In [18]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np
import glob

# Number of flights taking off from Boston
data=pd.read_csv("Flight Data/September_2016.csv")[["ORIGIN_CITY_NAME", "AIRLINE_ID", "DEST_CITY_NAME", "WEATHER_DELAY", "FL_DATE"]]
airdata = pd.read_csv("Flight Data/Airline_LOV.csv")[["AIRLINE_ID", "CARRIER_NAME"]]
df = DataFrame(data[data.apply(lambda x: x['ORIGIN_CITY_NAME'] == "Boston, MA", axis=1)])

data.to_csv('newdata.csv', sep=',', encoding='utf-8')

In [19]:
df1 = airdata.drop_duplicates()
df1

      AIRLINE_ID                                       CARRIER_NAME
0          19031                          Mackey International Inc.
1          19032                        Munz Northern Airlines Inc.
2          19033                              Cochise Airlines Inc.
3          19034                          Golden Gate Airlines Inc.
4          19035                                      Aeromech Inc.
5          19036                           Golden West Airlines Co.
6          19037                          Puerto Rico Intl Airlines
7          19038                                   Air America Inc.
8          19039                              Swift Aire Lines Inc.
9          19040                          American Central Airlines
10         19041                                    Valdez Airlines
11         19042                          Southeast Alaska Airlines
12         19043                               Altair Airlines Inc.
13         19044                                Chitina Air Service
14         19045                          Marco Island Airways Inc.
15         19046                        Caribbean Air Services Inc.
16         19047                                  Sundance Airlines
17         19048                         Seair Alaska Airlines Inc.
18         19049                            Southeast Airlines Inc.
19         19050                        Alaska Aeronautical Indust.
20         19051                             Imperial Airlines Inc.
21         19052                        Trans Western Airlines Utah
22         19053                               Wright Airlines Inc.
23         19054                               Presidential Express
24         19055                        Mississippi Valley Airlines
25         19056                                Channel Flying Inc.
26         19057                        Rocky Mountain Airways Inc.
27         19058                             Midstate Airlines Inc.
28         19059                        Sedalia Marshall Boonvl Stg
29         19060                                     Inlet Airlines
...          ...                                                ...
2540       21669  Aviation Partners of Boynton Beach LLC d/b/a H...
2541       21670              Fast Colombia SAS d/b/a Viva Colombia
2542       21672                                  Inselair Aruba NV
2543       21673  J&M Alaska Air Tours, Inc. d/b/a Alaska Air Tr...
2544       21674  Compagnie Aerienne Inter Regionale Express dba...
2545       21677                Cebu Air Inc d/b/a Cebu Pacific Air
2546       21692                           Azerbaijan Airlines CJSC
2547       21693                                      Cavok Air LLC
2548       21694                             Silk Way West Airlines
2549       21697                                  Orenburg Airlines
2550       21702                                WestJet Encore Ltd.
2551       21707                         Hong Kong Airlines Limited
2552       21712                                  Elite Airways LLC
2555       21718                           Delux Public Charter LLC
2556       21728                                     Eurowings GmbH
2557       21733                                 Abelag Aviation AG
2558       21735                             Longtail Aviation Ltd.
2559       21738                                         Air Serbia
2560       21743                           Tropic Ocean Airways LLC
2561       21745    LIMA NY Corp d/b/a Fly The Whale d/b/a Tailwind
2562       21749                             Talofa Airways Limited
2563       21754                                         21 Air LLC
2566       21760                                    Luxaviation S A
2567       21764  Trans Northern Airways d/b/a Air Unlimited Cha...
2568       21770                          Xiamen Airlines Co., Ltd.
2569       21774  Air Philippines Corp d/b/a Airphil Express, Ph...
2570       21780                              Cargologicair Limited
2571       21781                                 Eastar Jet Co Ltd.
2572       21785                  Hong Kong Express Airways Limited
2573       21809               Maine Aviation Aircraft Charter, LLC

[1715 rows x 2 columns]

In [17]:
import datetime
weatherdata = pd.read_csv("Flight Data/Weather data.csv")[["CLDATE", "SNWD", "SNOW"]]

# df = DataFrame(weatherdata[weatherdata.apply(lambda x: x['CLDATE'] == "", axis=1)])
weatherdata.head()

   CLDATE  SNWD  SNOW
0  1/1/16   0.0   0.0
1  1/2/16   0.0   0.0
2  1/3/16   0.0   0.0
3  1/4/16   0.0   0.0
4  1/5/16   0.0   0.0

In [20]:
df = df.merge(weatherdata, left_on='FL_DATE')
df.head()

TypeError: object of type 'NoneType' has no len()

In [43]:
df.iloc[0]['AIRLINE_ID']
airFilterData=airdata[airdata.AIRLINE_ID==19790]
airFilterData

     AIRLINE_ID          CARRIER_NAME
837       19790  Delta Air Lines Inc.
838       19790  Delta Air Lines Inc.
839       19790  Delta Air Lines Inc.
840       19790  Delta Air Lines Inc.

In [ ]:
# Number of flights landing in Boston
data=pd.read_csv("D:/Academics/Assignments/Harish-Git/Gunasekaran_Harish_spring2017/Final Exam/Flight data/September_2016.csv")[["ORIGIN_CITY_NAME", "AIRLINE_ID", "DEST_CITY_NAME"]]
airdata = pd.read_csv("D:/Academics/Assignments/Harish-Git/Gunasekaran_Harish_spring2017/Final Exam/Flight data/Airline_LOV.csv")
df = DataFrame(data[data.apply(lambda x: x['DEST_CITY_NAME'] == "Boston, MA", axis=1)])
df = pd.merge(df, airdata, on="AIRLINE_ID", how='left')
df = DataFrame(df.groupby(["AIRLINE_ID", "CARRIER_NAME"])["DEST_CITY_NAME"].count())
df